# Generated by Django 4.2.5 on 2024-03-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='сумма оплаты'),
        ),
    ]
