# Generated by Django 4.2.5 on 2024-03-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payments_payment_link_payments_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
